### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by macsim26** [BSCMike/FrontrunDeployer#2]

**Comment by np-wauxhall** [comment]
Bro it's a scam

**Comment by macsim26** [comment]
Yes i have read this fucker's code..
But thanks Bro

**Comment by macsim26** [comment]
> Bro it's a scam
Thanks...
I take a look at your repository and would like to ask with you about liquidity-sniper but there is no issue directory so how can i contact you? My mail is in my Github profile...
